export const PARTNER_ADD_REQUEST = "PARTNER_ADD_REQUEST";
export const PARTNER_ADD_SUCCESS = "PARTNER_ADD_SUCCESS";
export const PARTNER_ADD_FAIL = "PARTNER_ADD_FAIL";

export const PARTNER_DETAILS_REQUEST = "PARTNER_DETAILS_REQUEST";
export const PARTNER_DETAILS_SUCCESS = "PARTNER_DETAILS_SUCCESS";
export const PARTNER_DETAILS_FAIL = "PARTNER_DETAILS_FAIL";

export const PARTNER_UPDATE_REQUEST = "PARTNER_UPDATE_REQUEST";
export const PARTNER_UPDATE_SUCCESS = "PARTNER_UPDATE_SUCCESS";
export const PARTNER_UPDATE_FAIL = "PARTNER_UPDATE_FAIL";